### PR TITLE
Janitor: Fix typos in comments and user-facing strings

### PR DESCRIPTION
**Pull request by hunger**
No behavior change is intended!

### CODE REVIEW

**Comment by hunger** [comment]
@ogoffart , @tronical: Your CI is happy with these now, feel free to take a look.

I did also make sure that error messages do not end in a `.`. Most did already, so I removed the few trailing dots I could find.

**Review by ogoffart — APPROVED** [review]
thanks

**Comment by matklad** [comment]
> I did also make sure that error messages do not end in a .. Most did already, so I removed the few trailing dots I could find.

drive-by: might be a good idea to include debug_assert into the error-emitting code to check this.

**Comment by ogoffart** [comment]
Thanks for the suggestion: Done in commit f5de7e0

**Pull request merged**
