### PR TITLE
online editor trimming

### PR DESCRIPTION
**Pull request by tronical**
In late-night "rage coding" I decided to trim the online editor. This now uses vite for practically instant dev builds, removes unused programming languages from the Monaco editor (~14MB down to ~7MB) and tries to re-use the wasm interpreter from the website for website builds (from ~7MB down to ~2.3MB).

The latter I haven't been truly able to verify as I'm having mime type issues, but the relative paths are correct at least.

Please give it a try.

### CODE REVIEW

**Review by ogoffart — APPROVED** [review]
I must say my knowledge of web dev I'd not good enough to understand the details. But it all sound like a good idea

**Comment by ogoffart** [comment]
Are the instructions in the README in that folder still valid?

**Comment by tronical** [comment]
> Are the instructions in the README in that folder still valid?

Yes, they haven't changed.

**Comment by tronical** [comment]
There was an issue with the preview missing and the path to the wasm interpreter was wrong (worked locally, but not when deployed). Commit afb31d5c2eee278e5a6873fc9940630ca79cc9a0 fixed the files on the server.

**Pull request merged**
