### PR TITLE
Verify the existence of imported custom fonts

### PR DESCRIPTION
**Pull request by tronical**
... and produce diagnostics.

That way in later phases we don't need to check again.

### CODE REVIEW

**Comment by tronical** [comment]
Cherry-picked from the glyph pre-rendering branch. Since we had the discussion about import diagnostics in mattermost (regarding images) it reminded me that there's no reason to wait with this patch :)

**Review by ogoffart — APPROVED** [review]
I just wonder if we should have it a warning in the minor release.

**Comment by tronical** [comment]
> I just wonder if we should have it a warning in the minor release.

Fair question. On the other hand I think it will be an error later at compile time, so the sooner the error is reported the better IMO.

**Comment by tronical** [comment]
But I'm open to making this a warning, if you prefer.

**Pull request merged**
