### PR TITLE
Use `impl Default` instead of `new()` constructors

### PR DESCRIPTION
**Pull request by hunger**
The detault trait impl instead of `new()` patch separated out of the latest janitor patch set.

### CODE REVIEW

**Comment by tronical** [comment]
Singled out, this source incompatible change makes sense. I see two arguments against this though:

1. It seems more idiomatic to me to start a builder pattern with new() instead of default(). I thought Default is typically used for structs that don’t try to encapsulate anything.
2. new() has the advantage of being more extensible naming wise if the starting point of the builder pattern needs extension through an initial parameter in the future.

But I may very well be missing something about the intention of the Default trait, so no objections here - just curiosity to learn what’s idiomatic Rust API (as that’s the goal).

**Comment by hunger** [comment]
Clippy is the tool that teaches most programmers what ideonmatic rust is, so I do not argue with it on this topic :-) That leaves whether or not ideomatic rust is a good thing to have in these particular places.

I like `default()` to be used consistently, simply because I can never remember where to use `new()` and where `default()` otherwise:-) Plus the `Default` trait does enable some convenient things like `Option::unwrap_or_default`, etc.

**Comment by tronical** [comment]
In the standard library there are at least three builder pattern types (std::process::Command, std::fs::DirBuilder and std::thread::Builder) that don’t implement Default but use new() instead.

**Comment by tronical** [comment]
I’m torn. I see the one pattern all the time (winit is another example btw and rather popular), but I see clippy on the other hand.

**Comment by tronical** [comment]
@ogoffart  pointed out that we could have both, and I'm in favour of that. Implementing `Default` *and* keep the `new()` function, to get the best of both. Is that ok with you @hunger ?

**Comment by hunger** [comment]
Its definitely an option, yes:-)

**Comment by tronical** [comment]
Okay, great. Then I'll merge your change and re-add the `new()`.

**Review by tronical — APPROVED** [review]

**Pull request merged**
