### PR TITLE
Scripts: Generator for skeletons of weekly reports

### PR DESCRIPTION
**Pull request by hunger**
A bare bodes script that will just generate a html file (dated tomorrow)
containing the commits of the last seven days.

Use this as a skeleton for the "this week in sixtyfps" reports.

### CODE REVIEW

**Comment by tronical** [comment]
Apologies for the failed test. I need to fix the check / tags to separate the license (id) from the author/copyright.

**Comment by hunger** [comment]
@tronical: I guess I need to add a copyright statement in the first place?

**Comment by tronical** [comment]
For now you’d have to place the exact copyright and license text as in the other files. After #316 lands there can be your copyright, just the license text is required.

**Comment by hunger** [comment]
#329 has this script: I was stupid and tried to use the master branch for this and now I can not properly update this PR anymore:-( Sorry.

**Comment by ogoffart** [comment]
you can force push in PR

**Pull request closed without merging**
